-- 회원
CREATE TABLE IF NOT EXISTS MEMBER(
   MEM_ID SERIAL PRIMARY KEY
   , MEM_EMAIL VARCHAR(100) UNIQUE NOT NULL
   , MEM_PW VARCHAR(255) NOT NULL
   , MEM_NAME VARCHAR(30) NOT NULL
   , MEM_ROLE VARCHAR(30) NOT NULL DEFAULT 'USER'
   , CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   , MEM_STATUS VARCHAR(10) DEFAULT 'ACTIVE'
   , WARNING_CNT INT DEFAULT 0
   , BANNED_UNTIL TIMESTAMP
);

-- 게시글
CREATE TABLE IF NOT EXISTS POST (
	POST_ID INT PRIMARY KEY
	, POST_TITLE VARCHAR(100) NOT NULL
	, POST_CONTENT VARCHAR(1000) NOT NULL
	, IS_FILTERED CHAR(1) NOT NULL DEFAULT 'N'
	, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	, MEM_ID INT REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 게시글 이미지
CREATE TABLE IF NOT EXISTS POST_IMG(
	IMG_NUM SERIAL PRIMARY KEY
	, ORIGIN_IMG_NAME VARCHAR(100) NOT NULL
	, ATTACHED_IMG_NAME VARCHAR(100) NOT NULL
	, POST_ID INT REFERENCES POST (POST_ID) ON DELETE CASCADE
);

-- 댓글
CREATE TABLE IF NOT EXISTS CMT (
	CMT_ID SERIAL PRIMARY KEY
	, CMT_CONTENT VARCHAR(500) NOT NULL
	, CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	, IS_FILTERED CHAR(1) NOT NULL DEFAULT 'N'
	, POST_ID INT NOT NULL
	, MEM_ID INT NOT NULL
	, FOREIGN KEY (POST_ID) REFERENCES POST(POST_ID) ON DELETE CASCADE
	, FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID) ON DELETE CASCADE
);

-- 신고
CREATE TABLE IF NOT EXISTS REPORT (
	REPORT_ID SERIAL PRIMARY KEY
	, TARGET_TYPE VARCHAR(10) NOT NULL
	, TARGET_ID INT NOT NULL
	, REPORT_REASON VARCHAR(30) NOT NULL
	, REPORT_STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDING'
	, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	, REPORTER_ID INT NOT NULL
	, FOREIGN KEY (REPORTER_ID) REFERENCES MEMBER (MEM_ID)
	, UNIQUE (REPORTER_ID, TARGET_TYPE, TARGET_ID)
);

-- 제재
CREATE TABLE IF NOT EXISTS SANCTION (
	SANCTION_ID SERIAL PRIMARY KEY
	, SANCTION_TYPE VARCHAR(15) NOT NULL
	, SANCTION_REASON VARCHAR(50) NOT NULL
	, START_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	, END_DATE TIMESTAMP
	, MEM_ID INT NOT NULL
	, ADMIN_ID INT NOT NULL
	, FOREIGN KEY (MEM_ID) REFERENCES MEMBER (MEM_ID)
	, FOREIGN KEY (ADMIN_ID) REFERENCES MEMBER (MEM_ID)
);