CREATE TABLE MEMBER(
   MEM_ID INT PRIMARY KEY AUTO_INCREMENT  # 아이디
   , MEM_EMAIL VARCHAR(100) UNIQUE NOT NULL    # 이메일
   , MEM_PW VARCHAR(255) NOT NULL              # 비밀번호
   , MEM_NAME VARCHAR(30) NOT NULL             # 이름
   , MEM_ROLE VARCHAR(30) NOT NULL DEFAULT 'USER' # 권한
   , CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP  # 생성일
   , MEM_STATUS VARCHAR(10) DEFAULT 'ACTIVE' # 이용자 상태
   , WARNING_CNT INT DEFAULT 0               # 경고 횟수
   , BANNED_UNTIL TIMESTAMP                  # 정지일     
);

SELECT * FROM MEMBER;
ALTER TABLE MEMBER ADD MEM_STATUS VARCHAR(10) DEFAULT 'ACTIVE';
ALTER TABLE MEMBER ADD WARNING_CNT INT DEFAULT 0;

ALTER TABLE MEMBER ADD BANNED_UNTIL TIMESTAMP;