CREATE TABLE SECURITY_MEMBER(
	MEM_EMAIL VARCHAR(100) PRIMARY KEY
	, MEM_PW VARCHAR(20) NOT NULL
	, MEM_NAME VARCHAR(30) NOT NULL
	, MEM_ROLE VARCHAR(30) NOT NULL # 'USER', 'ADMIN', 'MANAGER'
);

SELECT * FROM SECURITY_MEMBER;

INSERT INTO SECURITY_MEMBER 
VALUES ('승형', '1234', '이승형', 'ADMIN'); 

UPDATE SECURITY_MEMBER
SET MEM_ROLE = 'ROLE_ADMIN'
WHERE MEM_EMAIL = '승형';

COMMIT;